name: Firebase Hosting CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your static files
      - uses: actions/checkout@v4

      # 2. Deploy directly to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with: 
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: xchat-958d4
          channelId: ${{ github.event_name == 'push' && 'live' || '' }}
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: xchat-958d4
          channelId: ${{ github.event_name == 'push' && 'live' || '' }}
